### PR TITLE
[cli] Upgrade launchModeExperimental to use estable launchMode

### PR DESCRIPTION
**Pull request by AlejandroGutierrezB**
## Description
Upgrade  launchModeExperimental to use stable launchMode property in app.json.ejs 

## Motivation and Context

Just house keeping to ensure repo is up to date

## How Has This Been Tested?
It's a non breaking change

### CODE REVIEW

**Comment by danstepanov** [comment]
@AlejandroGutierrezB You're missing a changeset https://github.com/roninoss/create-expo-stack/blob/main/contributing.md#make-your-changes

**Comment by AlejandroGutierrezB** [comment]
@danstepanov ups! fixed

**Comment by danstepanov** [comment]
@dannyhw lmk once you've reviewed

**Review by dannyhw — APPROVED** [review]
looks to be working. Thanks

**Pull request merged**
