### PR TITLE
[cli] chore: remove url polyfill

### PR DESCRIPTION
**Pull request by imranbarbhuiya**
## Description
This pr removes the URL polyfill as it's built-in in expo now

## Motivation and Context
Check https://docs.expo.dev/versions/latest/sdk/url/ for more info

### CODE REVIEW

**Comment by dannyhw** [comment]
is this built into to expo or is it in expo router? I thought it was added with the router

**Comment by imranbarbhuiya** [comment]
Their docs says
> This API is part of the expo package
I haven't tried it without router but seems like it's an expo feature and not expo-router

**Comment by dannyhw** [comment]
ok thanks for clarifying 👍

**Comment by danstepanov** [comment]
@dannyhw if you're good with this, we can test using the canary version?

**Comment by dannyhw** [comment]
Yeah sounds good. This looks fine to me.

**Pull request merged**
