### PR TITLE
Updating correct dependencies for nativewind.

### PR DESCRIPTION
**Pull request by Viraj-10**
While running `npx create-expo-stack@latest --nativewind`. I encountered some of the dependency bugs. 

### react-native-reanimated

- react-native-reanimated is dependency of `nativewind` v4 it should be installed.
    - Also you need to install specific version on react-native-reanimated which `3.10.1` otherwise it gives a version mismatch error since nativewind is dependant on that version. 

- react-native-safe-area-context is also a dependency of nativewind `next` so it should installed as well. 

I have included all the errors screenshot below. and package.json which worked for me. 

```js
{
  "name": "my-expo-app",
  "version": "1.0.0",
  "scripts": {
    "android": "expo start --android",
    "ios": "expo start --ios",
    "start": "expo start",
    "prebuild": "expo prebuild",
    "lint": "eslint \"**/*.{js,jsx,ts,tsx}\" && prettier -c \"**/*.{js,jsx,ts,tsx,json}\"",
    "format": "eslint \"**/*.{js,jsx,ts,tsx}\" --fix && prettier \"**/*.{js,jsx,ts,tsx,json}\" --write",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "^51.0.37",
    "expo-status-bar": "~1.12.1",
    "nativewind": "next",
    "react": "18.2.0",
    "react-native": "0.74.5",
    "react-native-reanimated": "3.10.1",
    "react-native-safe-area-context": "^4.11.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "@typescript-eslint/eslint-plugin": "^7.7.0",
    "@typescript-eslint/parser": "^7.7.0",
    "eslint": "^8.57.0",
    "eslint-config-universe": "^12.0.1",
    "prettier": "^3.2.5",
    "prettier-plugin-tailwindcss": "^0.5.11",
    "tailwindcss": "^3.4.0",
    "typescript": "~5.3.3"
  },
  "eslintConfig": {
    "extends": "universe/native",
    "root": true
  },
  "main": "node_modules/expo/AppEntry.js",
  "private": true
}

```

Screenshot 2024-10-11 at 3 57 38 PM
 
Screenshot 2024-10-11 at 3 58 14 PM

 
Screenshot 2024-10-11 at 3 56 55 PM

### CODE REVIEW

**Comment by dannyhw** [comment]
can you try 3.15.4 as the version? or adding overrides/resolutions to force the version

also could you explain the steps you took? was it causing the error directly from generating the project? or did you change anything else?

**Comment by dannyhw** [comment]
This seems correct but I'm not sure react-native-safe-area-context is required by nativewind 🤔

**Comment by Viraj-10** [comment]
@dannyhw, I was also wondering the same. Then I found out it is now required by nativewind. 
you can check out code [here](https://github.dev/nativewind/nativewind/tree/main/packages)

**Comment by dannyhw** [comment]
@Viraj-10 from that link I can't see it, what specifically is the place where you see that?

**Comment by Viraj-10** [comment]
@dannyhw it's a type import on line number 12.

**Comment by dannyhw** [comment]
the link does not take me to a specific file so I'm not sure what that means sorry

**Comment by Viraj-10** [comment]
@dannyhw, it's line number 31.

**Comment by Viraj-10** [comment]
@dannyhw, sorry for that here is a link https://github.com/nativewind/nativewind/blob/main/packages%2Freact-native-css-interop%2Fsrc%2Fruntime%2Fthird-party-libs%2Freact-native-safe-area-context.tsx#L31

**Comment by dannyhw** [comment]
I see well, from that code I can see that its only optionally called in certain cases, i.e if you use that functionality of the library so its an optional dependency

**Comment by Viraj-10** [comment]
Even though it's optional, the compiler will still throw an error about it.

**Comment by dannyhw** [comment]
image

Let me see what I can figure out for this

**Comment by dannyhw** [comment]
pushed a small fix for the duplicated deps

**Comment by danstepanov** [comment]
@dannyhw @Viraj-10 v4 is now latest for NativeWind (not announced yet) but you can just do `latest` now

**Comment by dannyhw** [comment]
updated to latest and generated changeset

**Pull request merged**
